---
- name: Atualização completa do sistema operacional
  hosts: all
  become: yes

  tasks:
    - name: Atualizar a lista de pacotes
      apt:
        update_cache: yes

    - name: Atualizar todos os pacotes do sistema
      apt:
        upgrade: full

    - name: Remover pacotes não utilizados
      apt:
        autoremove: yes

    - name: Limpar cache de pacotes
      apt:
        autoclean: yes

